{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  infrastructure:
    parametersRef:
      kind: LoadBalancerConfiguration
      name: {{ include "fastapi-app.fullname" . }}-lbconfig
      group: gateway.k8s.aws
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
